### ISSUE TITLE
Trying to make this work!

### ISSUE THREAD

**Issue by pgroot91** [dmott/custom-admin-pointers#1]
Would be nice to have a working example in the git or documentation! Anyway thanks for this will try to figure out how to make this work...

`function admin_pointers() {
	return array (
		'css_element_anchor' => '#post-search-input',
		'title' => 'something',
		'content' => 'content',
	);
}`

**Comment by dmott** [comment]
@pgroot91 In your theme's `functions.php` file make sure your `admin_pointers()` function is hooked by the `all_admin_pointers` filter, like so: `add_filter('all_admin_pointers', 'admin_pointers');`

Additionally, the array that filter should return should be an array of pointers, so like this:

```
function admin_pointers() {
  return array(
    array(
      'css_element_anchor' => '#post-search-input',
      'title' => 'some title',
      'content' => 'some content'
    )
  );
}
```

**Comment by pgroot91** [comment]
Thanks for the response will look into this later today to see if i can make this work! Much appreciated! 👍
